### PR TITLE
Fixed Feedback Error (fixed #188)

### LINKED ISSUE #188: Fixed Feedback Error
1. Edit layout.
2. Fixed can`t not find feedback error

### PR DESCRIPTION
**Pull request by MomentaryChen**
1. Default Encode UTF-8
2. Update Feedback Layout

### CODE REVIEW

File: server/src/main/java/fcu/selab/progedu/status/WebUnitTestFailure.java [hunk 1]
```diff
@@ -25,32 +25,42 @@ public String extractFailureMsg(String consoleText) {
...
+      endIndex = unitTestInfo.length();
+      ArrayList<FeedBack> feedbacklist = new ArrayList<>();
+      while (unitTestInfo.contains(")")) {
+        int nextparentheses = unitTestInfo.indexOf(")");
+        int nextrow = unitTestInfo.indexOf("\n", nextparentheses);
+        if (nextrow - nextparentheses == 1) { //
+          unitTestInfo = unitTestInfo.substring(nextrow + 1, endIndex);
+          endIndex = endIndex - nextrow - 1;
+        } else {
+          int netspace = unitTestInfo.indexOf("\n", nextparentheses + 1);
```
Comment (hoky841023) [inline server/src/main/java/fcu/selab/progedu/status/WebUnitTestFailure.java]: nextrow ?
netspace ?
nextparentheses ?

File: server/src/main/java/fcu/selab/progedu/status/WebStylelintFailure.java [hunk 2]
```diff
@@ -22,33 +22,50 @@ public String extractFailureMsg(String consoleText) {
...
+                  fileName,
+                  consoleText.substring(0, crossIndex - 1).trim(),
+                  errorString.substring(0, errorStyleStart + 1).trim(),
+                  errorString.substring(errorStyleStart, errorString.length()).trim(),
+                  "https://codertw.com/%E5%89%8D%E7%AB%AF%E9%96%8B%E7%99%BC/183114/\n"));
+          consoleText = consoleText.substring(nextRowIndex + 1, endIndex);
+          endIndex = endIndex - nextRowIndex - 1;
+        }
       }
+      return feedbackList;
```
Comment (hoky841023) [inline server/src/main/java/fcu/selab/progedu/status/WebStylelintFailure.java]: only one

File: server/src/main/java/fcu/selab/progedu/data/FeedBack.java [hunk 3]
```diff
@@ -55,6 +61,14 @@ public void setStyle(StatusEnum statusEnum) {
     this.status = statusEnum.getType();
   }
 
+  public String getfileName() {
```
Comment (hoky841023) [inline server/src/main/java/fcu/selab/progedu/data/FeedBack.java]: getFileName
